# Generated by Django 4.1.5 on 2023-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nickname',
            new_name='username',
        ),
    ]
