name: GitHub Actions
run-name: ${{ github.actor }}, GA working
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.0
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run Linter
        run: make lint
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
